id: P5F4362A1
initial_creation_type: ocr
source_metadata:
  volumes:
    b5e8c92e4d724103823e11cd77919e7b:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རྟོག་པ་ལས་གསུངས་པའི་ལྷ་མོ་རིགས་བྱེད་མའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
